### ISSUE TITLE
typo in rpcwallet.cpp

### ISSUE THREAD

**Issue by smaicloud** [swiftcashproject/swiftcash#16]
`"1. value   (numeric, required) Threshold value between 1 and 999999\n"`
_must be_
`"1. value   (numeric, required) Threshold value between 10000 and 100000\n"`

https://github.com/swiftcashproject/swiftcash/blob/83508fefb79d53ac8bdd4c4f0ec99f3875e3e604/src/rpcwallet.cpp#L2350

**Comment by swiftcashproject** [comment]
Will be fixed in the next release.
