### ISSUE TITLE
No macOS .app file

### ISSUE THREAD

**Issue by turcane** [swiftcashproject/swiftcash#2]
Please create a .app file for macOS like all the other wallets. Including Bitcoin and SmartCash.

**Comment by glemercier** [comment]
There is a builtin command to generate a .dmg file easily after building SwiftCash. The full build process looks like this:

```
$ ./autogen.sh
$ ./configure --disable-tests
$ make -j4
$ make deploy
```

The last command will automatically generate a `SwiftCash-Qt.app` directory and packaged `SwiftCash-Qt.dmg`

**Comment by turcane** [comment]
This works but it should ne be the usual way.
Not every user can or want to build it on his/her self.
