### ISSUE TITLE
SwiftCash-QT crashing on macOS

### ISSUE THREAD

**Issue by turcane** [swiftcashproject/swiftcash#3]
SwiftCash-QT wallet is crashing on macOS with error message

> Segmentation fault: 11

swiftcashd running fine

macOS Mohajve (10.14.1)

**Comment by glemercier** [comment]
It happens to me as well, I just try again and it usually works after 2-3 times.

**Comment by turcane** [comment]
Lucky guy. I need sometimes up to 30 tries until it starts.

**Comment by glemercier** [comment]
After I rebuilt it manually (see https://github.com/swiftcashproject/swiftcash/issues/2). It shows up every time without any issues. BTW I'm running High Sierra 10.13.6

**Comment by swiftcashproject** [comment]
The Mac crash apparently only happens on high sierra and the solution is a native build. We'll soon share a native build for high sierra for those who can't or don't want to build it themselves...

**Comment by swiftcashproject** [comment]
Native build for Mac(Highe Sierra) is now added to the release.
