### ISSUE TITLE
SwiftCash-QT still crashing on Mojave

### ISSUE THREAD

**Issue by turcane** [swiftcashproject/swiftcash#4]
NOT High Sierra, I'm talking about about Mojave (10.14.1)

> Process:               SwiftCash-Qt [33792]
> Path:                  /Applications/SwiftCash-Qt.app/Contents/MacOS/SwiftCash-Qt
> Identifier:            cc.swiftcash.SwiftCash-Qt
> Version:               1.0.0 (1.0.0)
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           SwiftCash-Qt [33792]
> User ID:               501
> 
> Date/Time:             2018-11-11 07:48:26.805 +0100
> OS Version:            Mac OS X 10.14.1 (18B75)
> Report Version:        12
> Bridge OS Version:     3.0 (14Y667)
> Anonymous UUID:        05BC9FD1-3228-3160-CCF2-E539B1D9AF78
> 
> Sleep/Wake UUID:       B91E911C-E6B7-4795-968D-858D969489AD
> 
> Time Awake Since Boot: 160000 seconds
> Time Since Wake:       110 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        0
> 
> Exception Type:        EXC_CRASH (SIGABRT)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Reason:    DYLD, [0x1] Library missing
> 
> Application Specific Information:
> dyld: launch, loading dependent libraries
> 
> Dyld Error Message:
>   Library not loaded: @loader_path/libboost_system-mt.dylib
>   Referenced from: /Applications/SwiftCash-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
>   Reason: image not found
> 
> Binary Images:
>        0x10c91b000 -        0x10d05bfff +cc.swiftcash.SwiftCash-Qt (1.0.0 - 1.0.0) <C954347F-2BAF-37E0-A99A-9FA3D5FE0AA3> /Applications/SwiftCash-Qt.app/Contents/MacOS/SwiftCash-Qt
>        0x10d11d000 -        0x10d174ff7 +libzmq.5.dylib (0) <177948E4-6B87-3FB4-8E9F-2501F466E7B7> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libzmq.5.dylib
>        0x10d184000 -        0x10d186ff7 +libboost_system.dylib (0) <5CFD618D-2AF4-3C59-88C2-B0CE6CCA7265> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libboost_system.dylib
>        0x10d18a000 -        0x10d198fff +libboost_filesystem.dylib (0) <E0F26994-D113-3440-9645-6E4FB91ABF19> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
>        0x10d1a1000 -        0x10d1d1fff +libboost_program_options-mt.dylib (0) <4280CB1D-C6B9-350D-B89E-5BBFFEBE8896> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
>        0x10d1ef000 -        0x10d1fbff7 +libboost_thread-mt.dylib (0) <2351B7AA-2ABC-370D-9E65-842C3781570B> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
>        0x10d20a000 -        0x10d20cfff +libboost_chrono-mt.dylib (0) <8FA281FE-6D12-3E2C-A7DE-F851F9C23F53> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
>        0x10d214000 -        0x10d31affb +QtNetwork (0) <CECCA1C7-8764-3738-8CC9-3F0ECC0BDCC6> /Applications/SwiftCash-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
>        0x10d365000 -        0x10d7a8fff +QtWidgets (0) <813C2F3F-FA7A-3468-8E2D-E3BB726A4CA6> /Applications/SwiftCash-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
>        0x10d90e000 -        0x10dd43fe3 +QtGui (0) <07AA0724-0329-3A68-BED8-B5342E39A2BB> /Applications/SwiftCash-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
>        0x10de45000 -        0x10e33cff7 +QtCore (0) <5EFD99B0-CFC9-3F53-9BE7-74B6BDBF1B8C> /Applications/SwiftCash-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
>        0x10e3f6000 -        0x10e456ffb +QtDBus (0) <A4848FFF-AE9A-37F7-9C33-8C2B66053D87> /Applications/SwiftCash-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
>        0x10e46f000 -        0x10e599feb +libprotobuf.17.dylib (0) <681916E6-DECE-3CD8-979F-E47FEF2BFEBA> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libprotobuf.17.dylib
>        0x10e64d000 -        0x10e761fff +libdb_cxx-4.8.dylib (0) <3DE30469-C467-3D53-A217-23AA2A2856C9> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
>        0x10e788000 -        0x10e7c7fff +libssl.1.0.0.dylib (0) <C81C0881-22EC-3DC7-A686-9C534A003B87> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
>        0x10e7e9000 -        0x10e95bd9f +libcrypto.1.0.0.dylib (0) <1E288AFF-8074-3191-9CC0-32539D7788BA> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
>        0x10e9c5000 -        0x10e9cdffb +libminiupnpc.17.dylib (0) <D83B2C71-0CFC-3324-92DC-ACD64DF63142> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libminiupnpc.17.dylib
>        0x10e9d1000 -        0x10e9d2fff +libevent_pthreads-2.1.6.dylib (0) <32AC3368-70B7-32B4-8465-50FA643C2649> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libevent_pthreads-2.1.6.dylib
>        0x10e9d5000 -        0x10ea01ff7 +libevent-2.1.6.dylib (0) <B4866E97-7CC4-3E15-BF2C-F667971CE7C7> /Applications/SwiftCash-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
>        0x11a631000 -        0x11a6af6a7  dyld (635.2) <1780094A-8FE2-3EAA-B4A3-C4CF14BC5196> /usr/lib/dyld
>     0x7fff3dd4d000 -     0x7fff3eb6dff3  com.apple.AppKit (6.9 - 1671.10.106) <179A5F4A-6467-31BD-93F2-CC27E046221E> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
>     0x7fff3ebbf000 -     0x7fff3ebbffff  com.apple.ApplicationServices (50.1 - 50.1) <470C0943-30AD-3BA2-AFCE-EB7DD26E1709> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
>     0x7fff407d8000 -     0x7fff40c25fe7  com.apple.CoreFoundation (6.9 - 1560.12) <B5BDC307-6C89-3DE0-B4B9-4C2C650E4528> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
>     0x7fff41a95000 -     0x7fff41a95fff  com.apple.CoreServices (934 - 934) <EBA4A3BF-0B07-3E1B-9C14-8E6879453C6C> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
>     0x7fff42b5d000 -     0x7fff42f2bfff  com.apple.Foundation (6.9 - 1560.12) <B5DC275C-12C9-320A-A117-C8FE9034931A> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
>     0x7fff6ae69000 -     0x7fff6ae6affb  libSystem.B.dylib (1252.200.5) <D5AFCC78-2AC2-37EB-B0EF-BB00FD38ED00> /usr/lib/libSystem.B.dylib
>     0x7fff6b0c3000 -     0x7fff6b11aff7  libc++.1.dylib (400.9.4) <D4AB366F-48A9-3C7D-91BD-41198F69DD57> /usr/lib/libc++.1.dylib
>     0x7fff6b11b000 -     0x7fff6b130fff  libc++abi.dylib (400.17) <BA948A32-9024-3E55-98D4-18E31F6AED25> /usr/lib/libc++abi.dylib
>     0x7fff6c90f000 -     0x7fff6d095fe7  libobjc.A.dylib (750.1) <9CE27EC3-3A12-35D1-8F2F-3550B9668259> /usr/lib/libobjc.A.dylib
>     0x7fff6d875000 -     0x7fff6d879ff3  libcache.dylib (81) <FE21A7E9-DBEB-33AC-836B-785AD036ACF4> /usr/lib/system/libcache.dylib
>     0x7fff6d87a000 -     0x7fff6d884ff3  libcommonCrypto.dylib (60118.220.1) <1099E427-6E81-3059-87AF-6F5FD81CA998> /usr/lib/system/libcommonCrypto.dylib
>     0x7fff6d885000 -     0x7fff6d88cfff  libcompiler_rt.dylib (63.4) <A4D9CF37-D076-3CE9-95F1-DA89DA1601B6> /usr/lib/system/libcompiler_rt.dylib
>     0x7fff6d88d000 -     0x7fff6d896ff3  libcopyfile.dylib (146.200.3) <4BCDADBF-79F5-3829-B47D-64DA0D44BCBF> /usr/lib/system/libcopyfile.dylib
>     0x7fff6d897000 -     0x7fff6d91bfdf  libcorecrypto.dylib (602.220.6) <E1046E01-A2FD-35B4-B018-ACC372F3880E> /usr/lib/system/libcorecrypto.dylib
>     0x7fff6d9a2000 -     0x7fff6d9dcff7  libdispatch.dylib (1008.220.2) <D8B56783-152A-34A8-94E9-8E6BAE049384> /usr/lib/system/libdispatch.dylib
>     0x7fff6d9dd000 -     0x7fff6da0cfff  libdyld.dylib (635.2) <1B79A5CE-125F-301F-A441-C1869573AED0> /usr/lib/system/libdyld.dylib
>     0x7fff6da0d000 -     0x7fff6da0dffb  libkeymgr.dylib (30) <A73AA788-C35C-3284-BFCA-95B1BBDF0CF3> /usr/lib/system/libkeymgr.dylib
>     0x7fff6da1b000 -     0x7fff6da1bff7  liblaunch.dylib (1336.220.5) <95EB6EAF-2DC5-344F-BADB-CA4E35E4E503> /usr/lib/system/liblaunch.dylib
>     0x7fff6da1c000 -     0x7fff6da21fff  libmacho.dylib (921) <ECC4E97C-575E-3A08-8191-BF02D7D4E637> /usr/lib/system/libmacho.dylib
>     0x7fff6da22000 -     0x7fff6da24ffb  libquarantine.dylib (86.220.1) <6AE5AEEC-A9FD-3CF8-92DD-12B5AFBE12DE> /usr/lib/system/libquarantine.dylib
>     0x7fff6da25000 -     0x7fff6da26ff3  libremovefile.dylib (45.200.2) <D74A307B-3DC7-3992-B16C-DACB8207BE13> /usr/lib/system/libremovefile.dylib
>     0x7fff6da27000 -     0x7fff6da3eff3  libsystem_asl.dylib (356.200.4) <EC9D8AD4-E5CB-3765-804A-9E1E9DC045D2> /usr/lib/system/libsystem_asl.dylib
>     0x7fff6da3f000 -     0x7fff6da3ffff  libsystem_blocks.dylib (73) <26419398-C30C-30F1-B656-A92AFA9560F6> /usr/lib/system/libsystem_blocks.dylib
>     0x7fff6da40000 -     0x7fff6dac8fff  libsystem_c.dylib (1272.200.26) <3DEEE96E-6DF6-35AD-8654-D69AC26B907B> /usr/lib/system/libsystem_c.dylib
>     0x7fff6dac9000 -     0x7fff6daccff7  libsystem_configuration.dylib (963.200.27) <02CC3996-B34E-333C-8806-AE2699D34424> /usr/lib/system/libsystem_configuration.dylib
>     0x7fff6dacd000 -     0x7fff6dad0ff7  libsystem_coreservices.dylib (66) <254B6849-2C8F-302C-8616-B8324A11AB30> /usr/lib/system/libsystem_coreservices.dylib
>     0x7fff6dad1000 -     0x7fff6dad7ffb  libsystem_darwin.dylib (1272.200.26) <974E9EF7-DE72-34B7-B056-0A81C10DF8EB> /usr/lib/system/libsystem_darwin.dylib
>     0x7fff6dad8000 -     0x7fff6dadeff7  libsystem_dnssd.dylib (878.200.35) <FFC665AA-B257-35AD-BD8B-32FD42C2EEC1> /usr/lib/system/libsystem_dnssd.dylib
>     0x7fff6dadf000 -     0x7fff6db2bff3  libsystem_info.dylib (517.200.9) <0707C387-D7DE-372E-8FF1-3DE5C91932D6> /usr/lib/system/libsystem_info.dylib
>     0x7fff6db2c000 -     0x7fff6db53ff7  libsystem_kernel.dylib (4903.221.2) <0E882078-7330-3B49-AA5D-3CDB5645A4E5> /usr/lib/system/libsystem_kernel.dylib
>     0x7fff6db54000 -     0x7fff6db9fff7  libsystem_m.dylib (3158.200.7) <43D1796B-954F-37D6-B1AC-9D80DF0655A2> /usr/lib/system/libsystem_m.dylib
>     0x7fff6dba0000 -     0x7fff6dbc4ff7  libsystem_malloc.dylib (166.220.1) <3B196122-4E0D-3E3F-AA3E-5115B976DE26> /usr/lib/system/libsystem_malloc.dylib
>     0x7fff6dbc5000 -     0x7fff6dbd0ff3  libsystem_networkextension.dylib (767.220.1) <C54EB8F6-F305-3452-8DB1-F7DA6859AF8C> /usr/lib/system/libsystem_networkextension.dylib
>     0x7fff6dbd1000 -     0x7fff6dbd8fff  libsystem_notify.dylib (172.200.21) <BCCB222F-DC64-3954-A836-DCCE6659CA5A> /usr/lib/system/libsystem_notify.dylib
>     0x7fff6dbd9000 -     0x7fff6dbe2fef  libsystem_platform.dylib (177.200.16) <B75B04AD-69FE-3ADE-84D2-C17972FC8F49> /usr/lib/system/libsystem_platform.dylib
>     0x7fff6dbe3000 -     0x7fff6dbedfff  libsystem_pthread.dylib (330.220.2) <4958273C-4273-3501-8137-E44249E10D9C> /usr/lib/system/libsystem_pthread.dylib
>     0x7fff6dbee000 -     0x7fff6dbf1ff7  libsystem_sandbox.dylib (851.220.9) <4D6433A8-C703-3ED9-82EB-B9E481A0FD2F> /usr/lib/system/libsystem_sandbox.dylib
>     0x7fff6dbf2000 -     0x7fff6dbf4ff3  libsystem_secinit.dylib (30.220.1) <6C681113-8C48-3256-BEF6-0C3723DEB926> /usr/lib/system/libsystem_secinit.dylib
>     0x7fff6dbf5000 -     0x7fff6dbfcff7  libsystem_symptoms.dylib (820.227.2) <3147D594-F41F-35FD-BF0B-6B8B66A407DE> /usr/lib/system/libsystem_symptoms.dylib
>     0x7fff6dbfd000 -     0x7fff6dc12ff7  libsystem_trace.dylib (906.220.1) <D5045DC5-A165-3238-A470-1796F12BF84F> /usr/lib/system/libsystem_trace.dylib
>     0x7fff6dc14000 -     0x7fff6dc19ffb  libunwind.dylib (35.4) <41222EF6-2233-3CF4-947A-15D48CB8C030> /usr/lib/system/libunwind.dylib
>     0x7fff6dc1a000 -     0x7fff6dc4afff  libxpc.dylib (1336.220.5) <B2137772-E202-3656-A089-F6DD517007D5> /usr/lib/system/libxpc.dylib
> 
> Model: MacBookPro14,3, BootROM 185.0.0.0.0, 4 processors, Intel Core i7, 2,9 GHz, 16 GB, SMC 2.45f0
> Graphics: Intel HD Graphics 630, Intel HD Graphics 630, Built-In
> Graphics: Radeon Pro 560, Radeon Pro 560, PCIe
> Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
> Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
> AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x173), Broadcom BCM43xx 1.0 (7.77.61.1 AirPortDriverBrcmNIC-1305.2)
> Bluetooth: Version 6.0.9f2, 3 services, 27 devices, 1 incoming serial ports
> Network Service: USB 10/100/1000 LAN, Ethernet, en7
> Network Service: Wi-Fi, AirPort, en0
> USB Device: USB 3.0 Bus
> USB Device: iBridge
> Thunderbolt Bus: MacBook Pro, Apple Inc., 39.2
> Thunderbolt Bus: MacBook Pro, Apple Inc., 39.2

**Comment by turcane** [comment]
I've built natively on Mojave, this one is not crashing.
Shall I provide it?

**Comment by swiftcashproject** [comment]
A native wallet can be built on Mac 10.13+ using the following scripts: 
https://gist.github.com/swiftcashproject/4c97e8f1a23abc66c1c7078a205c7970

**Comment by glemercier** [comment]
See https://github.com/swiftcashproject/swiftcash/pull/11 that should fix the issue. macOS testers requested.
